/**********************************************************************
*
* Original Author: Samantha Stensland
* File Creation Date: February 11, 2019
* Description: This program controls functionality for Form7.
* It was originally generated by Microsoft Visual Studio and edited further.
*
**********************************************************************/

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace GUI_Home
{
    public partial class Form7 : Form
    {
        public Form7(Form6 lastPage)
        {
            InitializeComponent();
            lastPage.Hide();
            lastPage.Close();
        }

        // Back to home page
        private void button1_Click(object sender, EventArgs e)
        {
            this.Hide();
            Form1 f1 = new Form1();
            f1.ShowDialog();
            this.Close();
        }
    }
}
